data:
  augmentation:
    homographic:
      enable: false
    photometric:
      enable: true
      params:
        additive_gaussian_noise:
          stddev_range:
          - 0
          - 10
        additive_shade:
          kernel_size_range:
          - 100
          - 150
          transparency_range:
          - -0.5
          - 0.5
        additive_speckle_noise:
          prob_range:
          - 0
          - 0.0035
        motion_blur:
          max_kernel_size: 3
        random_brightness:
          max_abs_change: 50
        random_contrast:
          strength_range:
          - 0.5
          - 1.5
      primitives:
      - random_brightness
      - random_contrast
      - additive_speckle_noise
      - additive_gaussian_noise
      - additive_shade
      - motion_blur
  cache_in_memory: false
  labels: outputs/mp_synth-v11_export_ha2
  name: coco
  validation_size: 96
  warped_pair:
    enable: true
    params:
      allow_artifacts: true
      max_angle: 1.57
      patch_ratio: 0.85
      perspective: true
      perspective_amplitude_x: 0.2
      perspective_amplitude_y: 0.2
      rotation: true
      scaling: true
      scaling_amplitude: 0.2
      translation: true
    valid_border_margin: 3
model:
  batch_size: 3
  detection_threshold: 0.001
  eval_batch_size: 3
  lambda_d: 800
  lambda_loss: 1
  learning_rate: 0.0001
  name: super_point
  negative_margin: 0.2
  nms: 4
  positive_margin: 1
  top_k: 600
train_iter: 300000
validation_interval: 5000
