data:
  add_augmentation_to_test_set: false
  augmentation:
    homographic:
      enable: true
      params:
        allow_artifacts: true
        max_angle: 1.57
        patch_ratio: 0.8
        perspective: true
        perspective_amplitude_x: 0.2
        perspective_amplitude_y: 0.2
        rotation: true
        scaling: true
        scaling_amplitude: 0.2
        translation: true
        translation_overflow: 0.05
      valid_border_margin: 2
    photometric:
      enable: true
      params:
        additive_gaussian_noise:
          stddev_range:
          - 0
          - 15
        additive_shade:
          kernel_size_range:
          - 50
          - 100
          transparency_range:
          - -0.5
          - 0.8
        additive_speckle_noise:
          prob_range:
          - 0
          - 0.0035
        motion_blur:
          max_kernel_size: 7
        random_brightness:
          max_abs_change: 75
        random_contrast:
          strength_range:
          - 0.3
          - 1.8
      primitives:
      - random_brightness
      - random_contrast
      - additive_speckle_noise
      - additive_gaussian_noise
      - additive_shade
      - motion_blur
  cache_in_memory: true
  name: synthetic_shapes
  preprocessing:
    blur_size: 21
    resize:
    - 120
    - 160
  primitives: all
  suffix: v6
  truncate:
    draw_ellipses: 0.3
    draw_stripes: 0.2
    gaussian_noise: 0.1
  validation_size: 500
eval_iter: 200
model:
  batch_size: 64
  detection_threshold: 0.001
  eval_batch_size: 50
  kernel_reg: 0.0
  learning_rate: 0.001
  name: magic_point
  nms: 4
seed: 0
train_iter: 50000
validation_interval: 1000
